eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://service-registry-container:8761/eureka
#             defaultZone: http://service-registry-container:8761/eureka
#     instance:
#         hostname: localhost
