eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
#             defaultZone: http://service-registry-container:8761/eureka
    instance:
        hostname: localhost
#         hostname: service-registry-container
