eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://config-server-container:8761/eureka
#             defaultZone: http://172.30.0.2:8761/eureka
    instance:
        hostname: config-server-container
#         hostname: 172.30.0.2
