eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://config-server-container:8761/eureka
#    instance:
#        hostname: localhost
