server:
  port: 9191

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**, /token

          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userServiceFallBack

        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: department-service
                fallbackuri: forward:/departmentServiceFallBack
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream





